spring.application.name=backend-graphql
server.port=8082

spring.datasource.url=jdbc:h2:mem:graphqldb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.graphql.graphiql.enabled=true
spring.graphql.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173
spring.graphql.cors.allowed-methods=GET,POST,OPTIONS
spring.graphql.cors.allowed-headers=*

